package xyz.ipiepiepie.semidimentional.gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import xyz.ipiepiepie.semidimentional.Main;

import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.*;
import java.io.File;

public class Menu extends JFrame {
    // input //
    private JPanel panel;
    private JButton attachButton;
    private JFileChooser fileChooser;
    // output //
    private JTextArea output;
    private JButton calculate;
    
    /**
     * Menu constructor
     */
    public Menu() {
        this.setTitle("2-D array order test");
        this.setContentPane(panel);
        this.setVisible(true);
        this.pack();
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        
        createListeners();
    }
    
    /**
     * Create button listeners
     */
    private void createListeners() {
        // attach input file button
        attachButton.addActionListener(action -> {
            fileChooser = new JFileChooser();
            fileChooser.setFileFilter(new FileNameExtensionFilter("Text file", "txt", "md"));
            fileChooser.showOpenDialog(panel);
        });
        
        // calculate button
        calculate.addActionListener(action -> {
            File input = fileChooser != null ? fileChooser.getSelectedFile() : null;
            
            if (input == null) {
                output.setEnabled(false);
                output.setText("Please, attach valid file!");
            } else {
                output.setEnabled(true);
                output.setText(String.format("Array is%s", Main.isOrdered(input) ? " ordered (true)" : "n't ordered (false)"));
            }
        });
    }
    
    
    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }
    
    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new GridLayoutManager(4, 2, new Insets(5, 5, 5, 5), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("Choose 2-D array file");
        panel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        attachButton = new JButton();
        attachButton.setText("Attach file");
        panel.add(attachButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel.add(spacer1, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        calculate = new JButton();
        calculate.setEnabled(true);
        calculate.setText("Test selected array");
        panel.add(calculate, new GridConstraints(3, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        output = new JTextArea();
        output.setColumns(0);
        output.setEditable(false);
        output.setEnabled(false);
        output.setRows(0);
        output.setText("Waiting for test results...");
        panel.add(output, new GridConstraints(2, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 10), null, 0, false));
    }
    
    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
    
}
